# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: nextvaldataBlogSecrets_update

stages:
- stage: BuildBlog
  displayName: 'Build Blog'
  jobs:
  - job: BuildJob
    displayName: 'Build Site'
    steps:
    - checkout: self
      persistCredentials: true
    - task: CmdLine@2
      displayName: 'Install Jekyll Dependencies (Bundler)'
      inputs:
        script: |
          gem install bundler
          bundle install
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: CmdLine@2
      displayName: 'Build Jekyll Site'
      inputs:
        script: 'bundle exec jekyll build --destination "$(Build.ArtifactStagingDirectory)/$(jekyllOutputFolder)"'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Built Site Artifact'
      inputs:
        PathtoPublish: '_site'
        ArtifactName: '$(artifactName)'
        publishLocation: 'Container'

- stage: DeployToGitHubPages
  displayName: 'Deploy to GitHub Pages'
  dependsOn: BuildBlog
  condition: succeeded()
  jobs:
  - job: DeployJob
    displayName: 'Push to GitHub Pages'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: $(artifactName)
      displayName: 'Download Built Site Artifact'
    - task: PowerShell@2
      displayName: 'Push to GitHub Pages'
      inputs:
        targetType: 'inline'
        scriptFilename: 'deploy.ps1'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
      env:
        GITHUB_PAT: $(GITHUB_PAT)
        ARTIFACTNAME: $(artifactName)
        GITHUBPAGESBRANCH: $(githubPagesBranch)
        BUILD_REPOSITORY_NAME: $(Build.Repository.Name)
        BUILD_BUILDID: $(Build.BuildId)
        PIPELINE_WORKSPACE: $(Pipeline.Workspace)