name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main # or your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # or your desired Ruby version
          bundler-cache: true # Cache bundler dependencies

      - name: Install Dependencies
        run: bundle install

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          force_orphan: true # Optional: Creates an empty gh-pages branch if it doesn't exist
